title: VUI-AD-HOC-ALEXA-RECOGNIZER
author: RationalAnimal (Ilya Shubentsov)
email: ilyafornpmpublishing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Node.js module for building voice skills and chat bots

github_username:  RationalAnimal

sass:
    style: compressed

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
